Opetushallitus/ehoks-ui

src/components/HomeLink.tsx, src/routes/Ammattitutkinto.tsx, src/routes/Henkilokohtaistaminen.tsx
Added back to frontpage links to Henkilökohtaistaminen and Ammatilliset tutkinnot -sections.
=> EH-129: Added back to frontpage links 

oppija/src/routes/OmienOpintojenSuunnittelu/Opiskelusuunnitelma.tsx, shared/components/Accordion.tsx, shared/components/ProgressPie.tsx
Now clicking category's title in progress status also opens corresponding section.
=> EH-211: Opiskelusuunnitelma progress status style improvements

.travis.yml
Fix Travis for new monorepo structure
=> Travis config changes

oppija/src/config.ts, oppija/webpack.config.js, virkailija/src/config.ts, virkailija/src/routes/LuoHOKS.tsx, virkailija/webpack.config.js
Pathien päivitys backend splitin jäljiltä.
Liittyy: https://github.com/Opetushallitus/ehoks/pull/125
=> Eh 322 split backend

virkailija/src/routes/App.tsx
=> EH-414: Forward to login instead of GET

oppija/src/stores/__tests__/__snapshots__/RootStore.test.ts.snap, shared/fetchUtils.ts, virkailija/src/routes/KoulutuksenJarjestaja.tsx, virkailija/src/stores/KoulutuksenJarjestajaStore.ts, virkailija/src/stores/SessionStore.ts
Oppijoiden latauksen korjaus ja oppilaitoksen valinta
=> Eh 415 fix oppija get

oppija/src/stores/HOKSStore.ts, shared/components/OrganisationDropdown.tsx, shared/components/Table/TableCell.tsx, shared/models/HOKS.ts, virkailija/src/routes/KoulutuksenJarjestaja.tsx, virkailija/src/routes/KoulutuksenJarjestaja/KoulutuksenJarjestajaHOKS.tsx
* Ensure that user has logged in and browser has fully finished loading organisations before fetching students. 
* Show organisations list sorted by organisation name. 
* Show message if selected organisation does not have any students.
=> EH-534: Fixed loading organisations and students

virkailija/src/stores/SessionStore.ts
Move setting selected organisation after all loading and use organisations array
=> Fix organisations storing

virkailija/src/stores/KoulutuksenJarjestajaStore.ts
Laitettu kommentteihin aikaisemmin toteutettu tuki eri käännöksille liittyen oppijan tutkintoon ja osaamisalaan. Pitää korjata kannasta data ennen kuin tämä voidaan ottaa käyttöön.
=> Eh 589 temp fix

oppija/src/routes/App.tsx, shared/localeUtils.ts, virkailija/src/routes/App.tsx
Lisätty querystringistä kieliparametrin parsiva util ja laitettu oppijan ja virkailijan puolille se localenvalinnan yhteyteen.
=> Eh 635 kielen vaihtaminen parametrilla

shared/components/Opiskelija/Tavoitteet.tsx
Ei näytetä selitettä jos urasuunnitelmaa ei ole asetettu oppijalle
=> EH-685: Hide empty career plan

shared/components/Opiskelija/Opiskelusuunnitelma.tsx, shared/components/StudyInfo.tsx, shared/components/StudyInfo/Details.tsx, shared/components/StudyInfo/LearningPeriod.tsx, shared/models/helpers/TutkinnonOsa.ts
Lisätty puuttuvia tietoja (ohjaajan sähköposti, työpaikan y-tunnus) opintojaksoihin.
=> Eh 704 monen ympariston puuttuvat tiedot

shared/components/Opiskelija/Opiskelusuunnitelma.tsx, shared/components/StudyInfo.tsx, shared/components/StudyInfo/Details.tsx, shared/components/StudyInfo/LearningEvent.tsx, shared/components/StudyInfo/LearningPeriod.tsx, shared/models/helpers/TutkinnonOsa.ts
Lisätty koulutuksen järjestäjän edustajan tiedot
=> Eh 705 jarjestajan edustaja ajanjakson tarkenne

shared/components/StudyInfo/Details.tsx, shared/components/StudyInfo/OtherPeriod.tsx, shared/models/helpers/TutkinnonOsa.ts
Listataan muut oppimisympäristöt opintojen yksityiskohtaisemmassa näkymässä
=> Eh 725 muu oppimisymparisto tieto

shared/models/helpers/TutkinnonOsa.ts, shared/models/helpers/getHarjoittelujaksot.ts
Jakson tyyppi päätellään oppimisenhankkimistapaKoodiUrista (oppilaitosmuotoinen, koulutussopimus jne) eikä katsomalla onko jaksolla muita oppimisympäristöjä.
=> EH-724: Fix learning period type deducing

shared/components/StudyInfo/Competences.tsx, shared/components/StudyInfo/Demonstration.tsx, shared/components/StudyInfo/LearningPeriod.tsx, shared/responsive.tsx, shared/styled.ts, shared/theme.ts
Create HMediaQuery component using react-responsive useMediaQuery and Styled Components withTheme
- Breakpoints are the highest resolution of the named device
Using static methods: `SmallTablet | Tablet | Desktop | Large | Max`
`<HMediaQuery.SmallTablet></HMediaQuery.SmallTablet>`
Or: `MaxWidth | MinWidth`
`<HMediaQuery.MinWidth breakpoint="SmallTablet"></HMediaQuery.MinWidth>`
=> Eh 737 hoksmediaquery responsive helper component

oppija/src/routes/OmienOpintojenSuunnittelu.tsx, shared/theme.ts
Change location of 'Sulje HOKS'-button for mobile.
=> Eh 737 sulje hoks button mobile version

oppija/src/routes/App/AppNotifications.tsx, shared/components/FormattedDate.tsx, shared/components/HOKSInfo.tsx, shared/components/Opiskelija/StudyPlan/Opiskelusuunnitelma.tsx, shared/components/Opiskelija/Suunnitelma.tsx, shared/components/Opiskelija/Tavoitteet.tsx, shared/components/ShareDialog.tsx, shared/components/StudyInfo/LearningEvent.tsx, shared/components/StudyInfo/LearningPeriodDates.tsx, virkailija/src/routes/KoulutuksenJarjestaja.tsx
Create FormattedDate shared component to wrap date-fns parseISO and format functions
=> Eh 770 create formatteddate shared component

virkailija/src/routes/HOKSLomake/CustomBaseInput.tsx, virkailija/src/routes/HOKSLomake/CustomDatetimeWidget.tsx, virkailija/src/routes/HOKSLomake/formConfig.ts, virkailija/src/routes/MuokkaaHOKS/uiSchema.ts
- Create custom components for react-jsonschema-form to get paivitetty date modified without setting time manually to 00:00:00
- Show paivitetty at Muokkaa HOKSia with custom Datetime widget
=> Eh 569 add paivitetty to hoks editor

TECHNICAL_DECISIONS.md, oppija/src/routes/Ammatillinentutkinto.tsx, oppija/src/routes/App/AppHeader.tsx, oppija/src/routes/App/AppNotifications.tsx, oppija/src/routes/App/MobileMenu.tsx, oppija/src/routes/Etusivu.tsx, oppija/src/routes/Henkilokohtaistaminen.tsx, oppija/src/routes/OmienOpintojenSuunnittelu.tsx, oppija/src/routes/Saavutettavuusseloste.tsx, oppija/src/routes/Suunnittelu.tsx, shared/components/Checkbox.tsx, shared/components/ModalDialogs/Modal.tsx, shared/components/Opiskelija/Tavoitteet.tsx, shared/components/ShareDialog.tsx, shared/components/StudyInfo.tsx, shared/components/StudyInfo/Demonstration.tsx, shared/stores/ErrorStore.ts, virkailija/src/routes/Header.tsx, virkailija/src/routes/KoulutuksenJarjestaja/KoulutuksenJarjestajaHOKS.tsx, virkailija/src/routes/KoulutuksenJarjestaja/Opiskelija.tsx, virkailija/src/routes/KoulutuksenJarjestaja/ValitseHOKS.tsx, virkailija/src/routes/Yllapito.tsx, virkailija/src/stores/SessionStore.ts
Divided into multiple small commits.
I need to click around all the components from QA
=> Fix nulls and typescript typings

shared/models/NaytonJarjestaja.ts, shared/models/helpers/TutkinnonOsa.ts
Get organization data for naytonJarjestaja using oppilaitosOid
=> Eh 743 nayton jarjestaja enrichening

shared/components/Opiskelija/AiempiOsaaminen.tsx, shared/components/Opiskelija/StudyPlan/CompletedStudies.tsx, shared/components/Opiskelija/StudyPlan/PlannedStudies.tsx, shared/components/Opiskelija/StudyPlan/ScheduledStudies.tsx, shared/components/StudyInfo.tsx, shared/components/StudyInfo/Demonstration.tsx, shared/components/StudyInfo/Details.tsx, shared/components/StudyInfo/LearningEvent.tsx, shared/components/StudyInfo/LearningPeriod.tsx, shared/components/StudyInfo/OtherPeriod.tsx, shared/components/__tests__/StudyInfo.test.tsx, shared/models/NaytonJarjestaja.ts, shared/models/OsaamisenOsoittaminen.ts, shared/models/helpers/TutkinnonOsa.ts, shared/models/helpers/getNaytot.ts, shared/models/helpers/getTila.ts
Replaced Naytto with OsaamisenOsoittaminen. Naytto and temporary refactoring structures will be deleted in upcoming PR.
=> Eh 743 naytto replace

oppija/tsconfig.json, package-lock.json, package.json, virkailija/tsconfig.json
And Fix excluding copying tests to dist
=> Update rollbacked packages

shared/components/StudyInfo/LearningPeriod.tsx, shared/models/Oppilaitoshenkilo.ts
Added rooli info for järjestäjän edustaja
=> Eh 828 jarjestajan edustaja more data

shared/models/AiemminHankittuAmmatillinenTutkinnonOsa.ts, shared/models/AiemminHankittuPaikallinenTutkinnonOsa.ts, shared/models/AiemminHankitunYTOOsaAlue.ts, shared/models/EnrichOrganisaatioOid.ts, shared/models/HankittavaAmmatillinenTutkinnonOsa.ts, shared/models/HankittavaPaikallinenTutkinnonOsa.ts, shared/models/HankittavaYhteinenTutkinnonOsa.ts, shared/models/NaytonJarjestaja.ts, shared/models/Oppilaitoshenkilo.ts, shared/models/YhteisenTutkinnonOsanOsaAlue.ts
Added koulutuksenJarjestaja to all tutkinnonOsat. This data is fetched from organisaatio-palvelu using koulutuksen-jarjestaja-oid. Made EnrichOrganisaatioOid support fethcing using different property names.
=> Enrich koulutuksen jarjestaja

oppija/translations.json, shared/components/Opiskelija/AiempiOsaaminen.tsx, shared/components/Opiskelija/StudyPlan/CompletedStudies.tsx, shared/components/Opiskelija/StudyPlan/PlannedStudies.tsx, shared/components/Opiskelija/StudyPlan/ScheduledStudies.tsx, shared/components/StudyInfo.tsx, shared/components/StudyInfo/LearningPeriod.tsx, shared/models/Organisaatio.ts, shared/models/helpers/TutkinnonOsa.ts, virkailija/translations.json
Added hankkivan koulutuksen edustaja to studyInfo. Also possibility to add koulutuksenJarjastaja to studyInfo title. This isn't totally ready yet though so commented out for now.
=> Eh 842 hankkija and koulutuksenjarjestaja

.gitignore, oppija/src/config.ts, oppija/src/index.tsx, shared/fetchUtils.ts, shared/models/EnrichKoodiUri.ts, shared/models/EnrichOrganisaatioOid.ts, shared/models/HOKS.ts, shared/models/KoulutuksenJarjestajaOrganisaatio.ts, virkailija/src/config.ts, virkailija/src/index.tsx, virkailija/src/routes/HOKSLomake/fetchKoodiUris.ts
Ilman headereita olleisiin hakuihin lisätty headerit, vaihdettu erilliset oppijan ja virkailijan id:t yhteiseksi. Headereiden lisäyksen siistiminen ja refaktorointi tehdään myöhemmin.
=> Eh 833 puuttuvat caller idt

shared/components/Opiskelija/AiempiOsaaminen.tsx, shared/components/Opiskelija/StudyPlan/CompletedStudies.tsx, shared/components/Opiskelija/StudyPlan/PlannedStudies.tsx, shared/components/Opiskelija/StudyPlan/ScheduledStudies.tsx, shared/components/StudyInfo.tsx, shared/components/StudyInfo/LearningPeriod.tsx
Made hankkijan edustaja to be shown always. Added koulutuksenJarjestaja to tutkinnon osa title.
=> Eh 842 hankkija and koulutuksen jarjestaja refinement

package-lock.json, package.json, shared/components/Opiskelija/AiempiOsaaminen.tsx, shared/components/Opiskelija/StudyPlan/CompletedStudies.tsx, shared/components/Opiskelija/StudyPlan/Opiskelusuunnitelma.tsx, shared/components/Opiskelija/StudyPlan/PlannedStudies.tsx, shared/components/Opiskelija/StudyPlan/ScheduledStudies.tsx, shared/components/ProgressPie.tsx, shared/components/StudyInfo.tsx, shared/responsive.tsx, shared/styled.ts, shared/theme.ts, virkailija/src/routes/HOKSLomake/Step.tsx
- Update typings for Styled Components
- Do not export theme use it with Styled Components (`styled()` automatically gets props.theme)
=> Fix do not static import theme

oppija/translations.json, shared/components/StudyInfo/OsaamisenOsoittaminen.tsx, shared/theme.ts, virkailija/translations.json
- Add opiskelusuunnitelma.sisaltoTitle
- Update theme and fix styles to use theme at Demonstration
=> Eh 899 add opiskelusuunnitelma sisalto title

shared/components/StudyInfo/Details.tsx
Extracted rest of the details to smaller components.
=> Eh 897 more refactoring

oppija/translations.json, shared/components/StudyInfo.tsx, virkailija/translations.json
Fixed id and generated translations.json for Toteuttava koulutuksenjärjestäjä.
=> EH-842-translation-added

oppija/translations.json, shared/components/StudyInfo/Details.tsx, shared/components/__tests__/StudyInfo.test.tsx, shared/models/KoulutuksenJarjestajaArvioija.ts, shared/models/TodennettuArviointiLisatiedot.ts, virkailija/translations.json
Added aiemminHankitunOsaamisenArvioijat to tutkinnon osa details. Refactored some tests.
=> Eh 897 arvioijat

.eslintrc.js, oppija/src/index.tsx, oppija/src/routes/Ammattitutkinto/SearchResult.tsx, oppija/src/stores/HOKSStore.ts, shared/fetchUtils.ts, shared/styleguide/setup.ts, virkailija/src/index.tsx, virkailija/src/routes/HOKSLomake/CustomBaseInput.tsx, virkailija/src/routes/HOKSLomake/CustomBooleanRadioButtonWidget.tsx, virkailija/src/routes/HOKSLomake/CustomCheckboxWidget.tsx, virkailija/src/routes/HOKSLomake/ReactJSONSchemaForm.tsx, virkailija/src/stores/KoulutuksenJarjestajaStore.ts
- Configure eslint:recommended
- Update TODO comments for info when the code might be changed
=> Eh 896 eslint recommended

.eslintrc.js, package-lock.json, package.json, shared/components/ShareDialog.tsx
- Install and configure eslint-plugin-react-hooks
=> Eh 896 eslint react hooks

shared/components/Table/SearchableHeader.tsx, shared/components/Table/TableBody.tsx, shared/components/Table/TableCell.tsx
=> Eh 934 style fixes

virkailija/src/routes/HOKSLomake/CustomBaseInput.tsx, virkailija/src/routes/HOKSLomake/CustomDatetimeWidget.tsx, virkailija/src/routes/MuokkaaHOKS.tsx
Trim module-ids when editing existing HOKS through ui. Also fixed manual ui react console error.
=> EH-936-remove-module-ids-from-hoks-edit

shared/components/Opiskelija/AiempiOsaaminen.tsx, shared/components/Opiskelija/StudyPlan/CompletedStudies.tsx, shared/components/Opiskelija/StudyPlan/Opiskelusuunnitelma.tsx, shared/components/Opiskelija/StudyPlan/PlannedStudies.tsx, shared/components/Opiskelija/StudyPlan/ScheduledStudies.tsx, shared/components/Opiskelija/StudyPlan/StudyPlanHelpers.ts, shared/components/ShareDialog.tsx, shared/components/ShareDialog/API.ts, shared/components/TutkinnonOsa.tsx, shared/components/TutkinnonOsa/Details.tsx, shared/components/TutkinnonOsa/OsaamisenOsoittaminen.tsx, shared/models/AiemminHankittuAmmatillinenTutkinnonOsa.ts, shared/models/AiemminHankittuPaikallinenTutkinnonOsa.ts, shared/models/AiemminHankittuYhteinenTutkinnonOsa.ts, shared/models/AiemminHankitunYTOOsaAlue.ts, shared/models/HankittavaAmmatillinenTutkinnonOsa.ts, shared/models/HankittavaPaikallinenTutkinnonOsa.ts, shared/models/HankittavaYhteinenTutkinnonOsa.ts, shared/models/helpers/TutkinnonOsa.ts, shared/stores/NotificationStore.ts, shared/utils/shareParams.ts
Noniin, jeespox. Tässä haarassa siis
- Lisätty tutkinnonOsaTyyppi elikäs esmes HankittavaAmmatillinenTutkinnonOsa, sekä tutkinnonOsaId (eli uuid) mukaan ShareDialogille vietäväksi. 
- Lisätty myös osaamisenOsoittamisen vertailu, jotta ei näy usealle yhtäaikaa se modaali.
=> Eh 953 add tutkinnon osa tyyppi

oppija/src/routes/OmienOpintojenSuunnittelu.tsx, oppija/translations.json, shared/models/Opiskeluoikeus.ts
Added tutkinto name and oppilaitos name to top summary
=> Eh 968 top summary additional info

oppija/src/stores/__tests__/SessionStore.test.ts, oppija/src/stores/mocks/oppija_session1.json, oppija/src/stores/mocks/oppija_session_update_user_info1.json, oppija/src/stores/mocks/oppija_session_user_info1.json, shared/__tests__/fetchUtils.test.ts, shared/components/Opiskelija/Tavoitteet.tsx, shared/models/SessionUser.ts, shared/stores/mocks/session1.json, virkailija/src/stores/KoulutuksenJarjestajaStore.ts
=> Eh 825 common name removal

shared/components/Opiskelija/StudyPlan/DegreeProgress.tsx, shared/theme.ts
Use all yhteenveto as action to show tutkinnonsat
=> Eh 976 yhteenvedosta tutkinnonosaan

oppija/src/index.tsx, package-lock.json, package.json, tyopaikantoimija/src/index.tsx, virkailija/src/index.tsx
Open browser dev tools console in development build to view accessibility errors of current state of the UI
=> Eh 998 install react axe for accessibility dev testing

shared/models/YhteinenTutkinnonOsa/OsaAlueVastaus.ts
Yhteisten tutkinnon osien osa-alueisiin liittyy pakollisia ja valinnaisia osaamistavoitteita. Tällä hetkellä ei ole mahdollista tietää mitä valinnaisia opintoja opiskelija on suorittanut joten lasketaan osa-alueen laajuuteen ainoastaan pakolliset osaamistavoitteet.
=> Eh 747 filter only pakolliset osa alueet

oppija/src/index.tsx, oppija/src/stores/EducationProviderStore.ts, oppija/src/stores/EnvironmentStore.ts, oppija/src/stores/HOKSStore.ts, oppija/src/stores/OppilasStore.ts, oppija/src/stores/SessionStore.ts, shared/components/ShareDialog/API.ts, shared/createEnvironment.ts, shared/fetchUtils.ts, shared/models/Enrichment/EnrichKoodistoKoodiUri.ts, shared/models/Enrichment/EnrichOrganisaatioOid.ts, shared/models/Enrichment/EnrichTutkinnonOsaAndOsaAlueet.ts, shared/models/Enrichment/EnrichTutkinnonOsaKoodiUri.ts, shared/models/HOKS.ts, shared/stores/NotificationStore.ts, shared/stores/TranslationStore.ts, shared/types/StoreEnvironment.ts, tyopaikantoimija/src/index.tsx, tyopaikantoimija/src/stores/EnvironmentStore.ts, tyopaikantoimija/src/stores/SessionStore.ts, virkailija/src/index.tsx, virkailija/src/routes/HOKSLomake/fetchKoodiUris.ts, virkailija/src/routes/LuoHOKS.tsx, virkailija/src/routes/MuokkaaHOKS.tsx, virkailija/src/routes/Yllapito.tsx, virkailija/src/stores/EnvironmentStore.ts, virkailija/src/stores/KoulutuksenJarjestajaStore.ts, virkailija/src/stores/SessionStore.ts
Lisätty callerId kutsuihin joista se puuttui. Nimetty callerId funktio appendCalleriId:ksi. Funktioiden nimet tulisi olla verbejä.
=> Eh 1073 missing caller ids added

shared/models/Enrichment/EnrichTutkinnonOsaViitteet.ts
Eperusteiden tutkinnon osan viitteiden hausta puuttui vielä caller-id
=> EH-1073: Added caller id for eperusteet request

oppija/public/ehoks/piwik.js
Lisättiin oma piwik siteId myös testistudieinfo.fi-sivulle
=> added piwik siteid for testistudieinfo

oppija/src/routes/App.tsx, oppija/src/routes/Etusivu.tsx, oppija/src/stores/EnvironmentStore.ts, oppija/webpack.config.js
CAS redirect oli väärässä paikassa. Teki redirectin heti etusivulta eikä vasta sitten kun käyttäjä painaa kirjautumisnappia. Lisätty webpack configiin /cas-oppija proxytys
=> Eh 984 oppija login fix

oppija/src/index.tsx, shared/components/ShareLinkInfo.tsx, tyopaikantoimija/src/stores/ShareStore.ts
Lisätty osaamisalan näyttäminen. 
To do: lokalisointi niin, että käytetään sitä osaamisalaa, minkä kielisessä
kälissä on.
=> Eh 1086 add osaamisala

oppija/src/routes/Etusivu.tsx, oppija/src/routes/Suunnittelu.tsx
Estetty selaimen ohjaus shibboleth logout urliin jos cas-oppija feature flag on päällä.
=> Eh 984 cas logout refinement

virkailija/src/routes/Yllapito.tsx
Lisätty herätteen uudelleenlähetys hoks-id:llä ylläpitovälilehdelle
=> Eh 1100 aloitusherate yllapitoon

virkailija/src/routes/KoulutuksenJarjestaja/HOKSInfo.tsx
Piilotetaan teksti Sovittua osaamista ei vielä saavutettu jos osaamisen saavuttamisen pvm:ää ei ole annettu.
=> EH-1104: Don't show osaamisen saavuttamisen pvm if it's not given

shared/components/Opiskelija/Tavoitteet.tsx
Show urasuunnitelma text if available, otherwise show tavoitteet.urasuunnitelmaTIetoaEiOleTallennettu.
=> Remove unneeded subtitle.

oppija/translations.json, shared/components/Opiskelija/Tavoitteet.tsx, virkailija/src/routes/LuoHOKS/uiSchema.ts, virkailija/src/routes/MuokkaaHOKS/uiSchema.ts, virkailija/translations.json
https://jira.eduuni.fi/browse/OY-3815
=> OY-3815 Add tuva-opiskeluoikeus-oid

virkailija/src/routes/Yllapito.tsx
Fiksattu endpoint, joka jäi uupumaan pullarista https://github.com/Opetushallitus/ehoks-ui/pull/456. Mergeän suoraan masterille.
=> fix: API endpoint for oppija update

oppija/src/stores/SessionStore.ts, tyopaikantoimija/src/stores/SessionStore.ts, virkailija/src/routes/App.tsx, virkailija/src/routes/VirkailijaRaamit.tsx
This is a stripped down version of https://github.com/Opetushallitus/ehoks-ui/pull/452 .  I'm trying to minimise the moving parts.
Fix ehoks-ui so that the green navigation bar is rerendered if language is changed.
=> OY-4352: make navigation bar react to language changes

shared/models/HOKS.ts
Lähetä null-arvo organisaatio-oid -kentässä
https://jira.eduuni.fi/browse/OY-4647
=> OY-4647: Mahdollista HOKSin poistaminen jos opiskeluoikeus on mitätöity

package-lock.json, package.json
reverting styled-components upgrade 5.3.5 -> 5.3.7 as it broke the UI
This reverts commit d13aa499745321b284cffa3ae5db783df1bae4f8.
=> Revert "fix: package.json & package-lock.json to reduce vulnerabilities"

oppija/src/routes/App.tsx, oppija/src/routes/Etusivu.tsx, oppija/src/routes/OmienOpintojenSuunnittelu.tsx, oppija/src/routes/Suunnittelu.tsx, oppija/src/routes/Suunnittelu/IntroModalDialog.tsx, oppija/src/routes/__tests__/__snapshots__/App.test.tsx.snap, shared/components/Opiskelija/StudyPlan/Opiskelusuunnitelma.tsx, shared/components/Redirect.tsx, tyopaikantoimija/src/routes/App.tsx, tyopaikantoimija/src/routes/Etusivu.tsx, virkailija/src/routes/KoulutuksenJarjestaja.tsx, virkailija/src/routes/KoulutuksenJarjestaja/KoulutuksenJarjestajaHOKS.tsx, virkailija/src/routes/KoulutuksenJarjestaja/Opiskelija.tsx, virkailija/src/routes/KoulutuksenJarjestaja/Opiskelijapalaute.tsx, virkailija/src/routes/LuoHOKS.tsx, virkailija/src/routes/MuokkaaHOKS.tsx
EH-1619:n yhteydessä tehdyn refaktoroinnin viimeistelyä / korjauksia. [Edellinen PR](https://github.com/Opetushallitus/ehoks-ui/pull/468) tuli mergettyä vähän liian aikaisin, en ollutkaan testannut kaikkia näyttöjä, ja tähän jäi vielä aika paljon viilattavaa. Mutta nyt pitäisi olla kunnossa.
=> react-router -kirjastopäivityksen & UI:n refaktoroinnin viimeistely

virkailija/src/routes/Header.tsx
Tämän muutoksen pohjana pitää (tai voi) olla [refaktorointi/kirjastopäivitys](https://github.com/Opetushallitus/ehoks-ui/pull/468).
=> EH-1619: Kielenvaihtokomponentti

shared/components/Opiskelija/AiempiOsaaminen.tsx, shared/components/Opiskelija/StudyPlan/CompletedStudies.tsx, shared/components/Opiskelija/StudyPlan/PlannedStudies.tsx, shared/components/Opiskelija/StudyPlan/ScheduledStudies.tsx, shared/components/TutkinnonOsa.tsx, shared/components/TutkinnonOsa/TutkinnonOsaHelpers.ts
Aiemmin se on näytetty vain osaamisen osoittamisen alla. Lisätään myös tutkinnon osille (ja YTOn osa-alueille).
https://jira.eduuni.fi/browse/EH-1634
=> EH-1634: Näytä vaatimuksista-tai-tavoitteista-poikkeaminen -tieto myös tutkinnon osilla

package-lock.json, package.json, virkailija/src/routes/LuoHOKS.tsx, virkailija/src/routes/MuokkaaHOKS.tsx
- päivitetty whatwg-fetch viimeisimpään versioon
- asetetaan state promisen sisällä funktiona
https://jira.eduuni.fi/browse/EH-1708
=> EH-1708: Korjaa käyttöliittymän virheviestit

oppija/src/routes/Suunnittelu/StudentFeedbackModal.tsx
Lisätty parametri kyselylinkkiin vastauskanavan seurantaa varten.
=> EH-1750: Parametri kyselylinkkiin
