oppija/src/config.ts, oppija/src/index.tsx, oppija/src/routes/__tests__/App.test.tsx, oppija/src/stores/EducationProviderStore.ts, oppija/src/stores/EnvironmentStore.ts, oppija/src/stores/HOKSStore.ts, oppija/src/stores/OppilasStore.ts, oppija/src/stores/SessionStore.ts, oppija/src/stores/TyopaikanToimijaStore.ts, oppija/src/stores/__tests__/SessionStore.test.ts, shared/createEnvironment.ts, shared/stores/ShareLinkStore.ts, shared/stores/TranslationStore.ts, shared/stores/__tests__/TranslationStore.test.ts, shared/types/StoreEnvironment.ts, virkailija/src/config.ts, virkailija/src/index.tsx, virkailija/src/stores/EnvironmentStore.ts, virkailija/src/stores/KoulutuksenJarjestajaStore.ts, virkailija/src/stores/SessionStore.ts
Kummankin puolen configeihin on lisätty Caller-Id:n lisäävä tai olemassaoleviin headereihin sen appendaava funktio ja tämä on lisätty käyttöön jokaiseen fetchejä tekevään paikkaan.
Nimi callerId ei ole enää kauhean itsestäänselvä, kun sille voi antaa parametriksi muut headerit, joten sen tilalle voisi kehittää jonkin fiksumman.
=> Eh 454 caller id tuki

oppija/src/routes/App.tsx, shared/localeUtils.ts, shared/stores/TranslationStore.ts
Lisätty localStorage localen säilömiseen, localen päättelyn prioriteettiketju on nyt: queryparametri -> localStorage -> default. Tallennetaan locale localStorageen myös joka kerta, kun TranslationStoren setActiveLocalea kutsutaan.
=> Eh 671 localen tallennus localstorageen

shared/models/HOKS.ts
Merkataan valmiiksi opinnoiksi vain ne joiden tila on `valmis` ja joiden osaamisen osoittamisen loppupäivästä on kaksi viikkoa
=> EH-716: Change completed studies handling

shared/models/HOKS.ts, shared/models/helpers/getTila.ts
Siirretty kahden viikon kulumisen tarkistus getTila.ts:ään minne se oikeasti kuuluisikin. Muutettu valmiiden filtteröintiä niin, että vain osaamisenOsoittaminen siirtää opinnon valmiiksi ja hankkimistavat sivuutetaan.
=> Fix filtering finished studies

README.md, oppija/webpack.config.js, package-lock.json, package.json, virkailija/webpack.config.js
**Affects only development builds.**
It will include component name in hashed classNames like `<div class="sc-pcLhl kBHwAC">` and replace these `styled.div` type naming in React inspector with component names.
Original Styled Components documentation supports babel-plugin, but now it can be handled with typescript plugin also. https://styled-components.com/docs/tooling#babel-plugin
=> Automatically show Styled Components component-names at DOM

virkailija/src/routes/KoulutuksenJarjestaja.tsx, virkailija/src/routes/KoulutuksenJarjestaja/Opiskelija.tsx, virkailija/src/routes/LuoHOKS.tsx, virkailija/src/routes/MuokkaaHOKS.tsx, virkailija/src/routes/Yllapito.tsx
Extend RouteComponentProps from Reach/Router to have more clear why and where these props come from. Add comments on props that are deriver from router path
=> Extend RouteComponentProps from Reach/Router

oppija/src/routes/OmienOpintojenSuunnittelu.tsx, oppija/src/stores/SessionStore.ts, oppija/src/stores/__tests__/SessionStore.test.ts, oppija/src/stores/__tests__/__snapshots__/RootStore.test.ts.snap, shared/components/Opiskelija/Tavoitteet.tsx, shared/models/SessionUser.ts, virkailija/src/stores/SessionStore.ts
This might be the first part of refactoring of technical debt related to TypeScript not finding issues.
- `OmienOpintojenSuunnittelu` was been rendered without `student: ISessionUser`.
- Removing `null`'s and using `undefined`'s as decided and used 3rd party libs suggest.
- Importing interfaces from models
=> Fix typescript issues with SessionStore

virkailija/src/routes/Yllapito.tsx, virkailija/translations.json
Elikäs, ylläpitovälilehdelle vaan yksi nappu, joka hakee bäkkäristä opiskeluoikeus-oidilla ehoks-id:n sekä sitten vaan kälille tulostus hoksien määrästä eli yksi fetch bäkkäristä. Tuo Ylläpito.tsx näkyy vain oph-super-usereille.
=> New buttons for yllapito

shared/components/Opiskelija/AiempiOsaaminen.tsx, shared/components/Opiskelija/StudyPlan/CompletedStudies.tsx, shared/components/Opiskelija/StudyPlan/PlannedStudies.tsx, shared/components/Opiskelija/StudyPlan/ScheduledStudies.tsx, shared/components/StudyInfo.tsx, shared/components/StudyInfo/Details.tsx, shared/components/StudyInfo/LearningPeriod.tsx, shared/components/__tests__/StudyInfo.test.tsx, shared/models/Oppilaitoshenkilo.ts, shared/models/OsaamisenHankkimistapa.ts, shared/models/helpers/HankittavatTutkinnonOsatViews.ts, shared/models/helpers/TutkinnonOsa.ts
OsaamisenHankkimistapa was previously converted to HarjoitteJaksot which caused confusion as Harjoittelujaksot isn't domain concept. Moved functionality from getHarjoittelujaksot to OsaamisenHankkimistapa and made components take array of OsaamisenHankkimistapa as a prop instead of Harjoittelujaksot array. Added temporary structures so that Harjoittelujaksot can be refactored away gradually. Those temp structures and harjoitteluJaksot will be deleted or renamed in a upcoming PR as this PR is already too big and needs to be integrated asap.
=> Eh 843 replace harjoittelujaksot

.dependabot/config.yml
Only security updates for production. Handle major updates or dev tool updates manually for now.
Could be possible later: https://github.com/dependabot/feedback/issues/433
=> Create config for debendabot

shared/components/StudyInfo/Demonstration.tsx, shared/components/__tests__/StudyInfo.test.tsx, shared/models/OsaamisenOsoittaminen.ts
Made järjestäjä visible only if it has a value. Removed unnecessary optional chaining as mst-model had default values. Made some default values explicit.
=> Eh 743 jarjestaja visibility

virkailija/src/routes/LuoHOKS/uiSchema.ts, virkailija/src/routes/MuokkaaHOKS/uiSchema.ts
Moved koulutuksen-jarjestaja-oid under osa-alue-koodi-uri from the bottom of the form that was the default position.
=> Manual UI reorder

doc/adr/0001-record-architecture-and-desing-decisions.md, doc/adr/0002-use-finnish-as-the-domain-language.md
Template to record architectural decisions. Added decision record to use Finnish as the domain language.
https://medium.com/better-programming/here-is-a-simple-yet-powerful-tool-to-record-your-architectural-decisions-5fb31367a7da
http://thinkrelevance.com/blog/2011/11/15/documenting-architecture-decisions
=> ADRs introduced

.eslintrc.js, oppija/src/routes/App.tsx, oppija/src/routes/App/MobileMenu.tsx, oppija/src/routes/Saavutettavuusseloste.tsx, package-lock.json, package.json, shared/components/Table.tsx, shared/components/Table/SearchableHeader.tsx, shared/components/icons/Flag.tsx, shared/components/icons/PenPaper.tsx, shared/components/icons/Ribbon.tsx, shared/components/icons/User.tsx, shared/components/react-jsonschema-form/TypeaheadField.tsx, shared/fetchUtils.ts, shared/models/EnrichKoodiUri.ts, shared/models/EnrichOrganisaatioOid.ts, shared/models/EnrichTutkinnonOsa.ts, shared/models/HOKS.ts, shared/responsive.tsx, shared/stores/NotificationStore.ts, shared/stores/ShareLinkStore.ts, shared/styleguide/StyleguidistWrapper.tsx, virkailija/src/routes/HOKSLomake/ArrayFieldTemplate.tsx, virkailija/src/routes/HOKSLomake/CustomBaseInput.tsx, virkailija/src/routes/HOKSLomake/CustomBooleanRadioButtonWidget.tsx, virkailija/src/routes/HOKSLomake/helpers/idToPathArray.ts, virkailija/src/routes/HOKSLomake/helpers/idToTranslationKey.ts, virkailija/src/routes/HOKSLomake/helpers/schemaToTranslations.ts, virkailija/src/stores/KoulutuksenJarjestajaStore.ts
- eslint-plugin-react
- @typescript-eslint/eslint-plugin
*react/no-string-refs* using string identifier is deprecaded and used in https://github.com/Opetushallitus/ehoks-ui/compare/eh-896-redefine-eslint-rules?expand=1#diff-3dc81b1e748108800d76cc83a46f7c64R247
More info:
https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-string-refs.md
https://github.com/ericgio/react-bootstrap-typeahead/blob/master/docs/Methods.md
=> Eh 896 redefine eslint rules

virkailija/src/routes/MuokkaaHOKS.tsx
Trim disallowed keys when fetching data for hoks edit ui. Removed trimming from save as edit ui now uses HOKSKorvaus schema and ensures that data sended to backend conforms to correct schema. However when fetching data for edit ui, API that is used returns data according to GET schema and would cause problems with react-json-schema-form uiSchema (uses HOKSKorvaus PUT schema) unless we trim disallowed keys at the fetch.
Renamed function to convey why we trim keys.
=> Fix to edit ui schema

oppija/src/stores/SessionStore.ts
Removed unnecessary call to a deprecated API. API would just return request values as is. A Valid session cookie is obtained after login when user comes to session/opintopolku route.
=> Removed call to a deprecated api

oppija/jest.config.js, tyopaikantoimija/jest.config.js, virkailija/jest.config.js
Made Jest search tests only from typescript files. 
Default for testMatch is [ "**/__tests__/**/*.[jt]s?(x)", "**/?(*.)+(spec|test).[jt]s?(x)" ] 
https://jestjs.io/docs/en/configuration#testmatch-arraystring
meaning js files would be searched also but we don't have need for that.
=> jest config change

shared/models/Enrichment/EnrichKoodistoKoodiUri.ts, shared/models/Enrichment/EnrichOrganisaatioOid.ts
Fixed two enrichers. Name of the property was passed instead of value.
=> Enrichment fix

virkailija/src/routes/Yllapito.tsx, virkailija/translations.json
Lisätty kaksi nappua ylläpitokäliin
- päivitä opiskeluoikeudet, joka kutsuu bäkkärin /opiskeluoikeus/:opiskeluoikeus-oid -apia (eli dellaa opiskeluoikeusindeksistä kyseisen opiskeluoikeuden ja sitten uudelleenindeksoi). 
- päivitä koulutustoimijan opiskeluoikeudet, joka kutsuu ensin /opiskeluoikeudet/:koulutustoimija-oid/deletion-info -apia ja näillä tiedoilla varmistaa käyttäjältä, että hän todella haluaa dellata kaikki x kpl opiskeluoikeutta ja indeksoida uudestaan ja ok:n jälkeen kutsutaan DELETE "/opiskeluoikeudet/:koulutustoimija-oid" apia, joka dellaa kaikki koulutustoimijan opiskeluoikeudet ja sitten pyöräyttää sen dellauksen uudestaan.
=> Eh 1036 opiskeluoikeuksien paivitys yllapito ui

shared/models/Enrichment/EnrichTutkinnonOsaAndOsaAlueet.ts, shared/models/YhteinenTutkinnonOsa/AiemminHankittuYhteinenTutkinnonOsa.ts, shared/models/YhteinenTutkinnonOsa/HankittavaYhteinenTutkinnonOsa.ts
Yhteisten tutkinnon osien mst-modeleihin sijoitettiin iso läjä eperusteista tulevaa dataa mutta oikeasti ainoa tarvittava tieto on tutkinnon osan id, jonka avulla osa-alueet rikastetaan. Poistettu ytoilta TutkinnonOsa property ja lisätty tutkinnonOsaId.
=> EH-747: Tutkinnon osa id from eperusteet

oppija/src/routes/Etusivu.tsx, oppija/src/routes/__tests__/__snapshots__/App.test.tsx.snap
Poistettu oppijan etusivun kirjautumislaatikolta banner aria role koska oli hämäävä. Banneria kuuluisi käyttää elementissä joka sisältää sivustokohtaista tietoa, ei sivukohtaista. Banneriin kuuluvaa tietoa on esim logo, firman nimi, slogan, hakuikoni.
=> Eh 1035 banner aria role removed

virkailija/src/stores/SessionStore.ts
Poistettu virkailijan sessionStoresta login funktio jota ei enää käytetty. Oli aiemmin käytössä mutta PR:ssä https://github.com/Opetushallitus/ehoks-ui/pull/48 muutettiin redirectiksi login urliin.
=> Deleted unused login funtion

oppija/src/index.tsx, oppija/src/routes/App.tsx, oppija/src/stores/EnvironmentStore.ts, oppija/src/stores/__tests__/__snapshots__/RootStore.test.ts.snap, shared/components/AppContext.tsx, tyopaikantoimija/src/index.tsx, virkailija/src/index.tsx
Oppijaan feature flagin taakse redirect cas-oppijan login urliin. Kun tämä otetaan käyttöön, nginx-reposta pitää ottaa pois shibbolethiin redirectaava konfiguraatio.
=> Eh 984 oppija cas

oppija/translations.json, shared/components/TutkinnonOsa/Competences.tsx, virkailija/translations.json
Korjattu hyton osa-alueiden osaamistavoitteiden otsikko kun osaamistavoitteet on laajennettu. Aiemmin luki Ammattitaitovaatimukset, nyt Osaamistavoitteet.
=> EH-748: Title fix

shared/components/Opiskelija/Tavoitteet.tsx
Näytetään oppijalle hoksiin tallennettu sähköposti eikä oppijanumerorekisteristä tuleva koska hoksiin tallennettua käytetään opiskelijapalautteen lähetykseen.
=> EH-1068: Oppija eEmail

shared/models/EPerusteetVastaus.ts, shared/models/YhteinenTutkinnonOsa/OsaAlueVastaus.ts, shared/models/helpers/getOsaamisvaatimukset.ts
Arvionninkohdealueet voi olla null eperusteista tulevassa vastauksessa. Näin on esimerkiksi TELMA-koulutuksen tapauksessa.
=> Eh 1074 telma fix

shared/models/YhteinenTutkinnonOsa/OsaAlueVastaus.ts
Osa-alueen laajuus voi olla null eperusteiden vastauksessa.
=> EH-1099: Laajuus can be null from eperusteet

shared/localeUtils.ts, virkailija/src/routes/HOKSLomake/BottomToolbar.tsx
Raamien linkit johtamaan siihen ympäristöön jossa ehoks sijaitsee. Chromelle suunnattu korjaus syöttökentän peittävään alapalkin nappulaan (firefoxilla toimi jo aiemmin oikein).
=> Oy 2728 ja oy 2818

virkailija/src/routes/Yllapito.tsx
Ylläpitosivulla "epäonnistunut"-viestit näkyivät vihreinä, vaikka niiden pitäisi olla punaisia. Tämä on korjaus siihen.
=> Epäonnistumisen värin pitää olla punainen ylläpitosivulla

virkailija/src/routes/App.tsx, virkailija/src/routes/Header.tsx, virkailija/src/routes/KoulutuksenJarjestaja.tsx, virkailija/src/routes/KoulutuksenJarjestaja/KoulutuksenJarjestajaHOKS.tsx, virkailija/src/routes/KoulutuksenJarjestaja/Opiskelija.tsx, virkailija/src/routes/KoulutuksenJarjestaja/ValitseHOKS.tsx, virkailija/src/routes/Raportit.tsx, virkailija/src/stores/KoulutuksenJarjestajaStore.ts
Tämänhetkinen tilanne: suorat linkit HOKSiin toimivat vain, jos linkin avaajalla sattuu olemaan (esim. localStoragessa) valittuna organisaatio, jolla on oikeus tarkastella kyseisen oppijan HOKSeja.
Haluttu tilanne: suorat linkit toimivat aina.
Tämä PR muuttaa kaikki virkailijan näkymät oppijaan ja oppijan HOKSeihin sellaisiksi, että URL-osoitteessa on mukana organisaatio, jonka kautta oppija löydettiin.  Kun näihin URLeihin sitten menee uudella selaimella / välilehdellä, virkailijalla aktiivinen (valittu) organisaatio asetetaan URL-osoitteen organisaatioksi, niin että oppija HOKSeineen löydetään jälleen.
PR rakentuu [tämän toisen korjauksen](https://github.com/Opetushallitus/ehoks-ui/pull/444) päälle (ja sisältää sen).
=> Add organisation OID to links and URLs in all HOKS viewing components

shared/components/KoulutuksenOsa.tsx, shared/components/Opiskelija/StudyPlan/CompletedStudies.tsx, shared/components/Opiskelija/StudyPlan/ScheduledStudies.tsx, shared/models/EPerusteetVastaus.ts
this PR needs https://github.com/Opetushallitus/ehoks/pull/524 to work.
=> TUVA: use koulutuksenOsa viiteId for deep linking to ePerusteet

virkailija/src/routes/LuoHOKS/uiSchema.ts, virkailija/src/routes/MuokkaaHOKS/uiSchema.ts
Kuten weeklyssa sovittiin, piilotetaan yksilöivä tunniste käyttöliittymässä.  Todennäköisesti se on vain unohtunut aikanaan tehdä; ihmisillä ei voi olla hyötyä sen syöttämisestä käsin, eikä varsinkaan muokkaamisesta.
https://jira.eduuni.fi/browse/EH-1472
❗ **Katselmoijat tarkastavat, että yllä mainitut kohdat toteutuvat**
- Jos muutoksilla voi jotain rikkoessaan olla kauaskantoiset vaikutukset, kannattaa muutokset hyväksyttää useammalla katselmoijalla
=> Hide yksiloiva tunniste from HOKS UI

oppija/translations.json, shared/models/AiemminHankittuAmmatillinenTutkinnonOsa.ts, shared/models/EPerusteetVastaus.ts, shared/models/Enrichment/EnrichTutkinnonOsaKoodiUri.ts, shared/models/HankittavaAmmatillinenTutkinnonOsa.ts, shared/models/HankittavaKoulutuksenOsa.ts, shared/models/YhteinenTutkinnonOsa/AiemminHankitunYTOOsaAlue.ts, shared/models/YhteinenTutkinnonOsa/OsaAlueVastaus.tsx, shared/models/YhteinenTutkinnonOsa/YhteisenTutkinnonOsanOsaAlue.ts, shared/models/helpers/AiemminHankitutTutkinnonOsatViews.ts, shared/models/helpers/HankittavatTutkinnonOsatViews.ts, shared/models/helpers/LocaleRoot.ts, shared/models/helpers/getOtsikko.tsx
- käsitellään tutkinnonosan haun vastaus eperusteista listana
- lisätään erilaisia vaihtoehtoja nimitiedolle, jos sitä ei löydy sieltä, mistä yleensä
- jos nimeä ei ollenkaan löydy, lisätään vaihtoehdoksi koodiUrin tai viime kädessä moduleId:n näyttäminen nimenä
- poistetaan kaikki sellainen logiikka, jossa otsikoksi palautetaan tyhjä merkkijono
- poistetaan kaikki sellainen logiikka, jossa merkkijonon olemassaolo päätellään jostain muusta kuin siitä, onko kyseinen merkkijono ei-tyhjä (esim. model-olioiden olemassaolosta jotka on kuitenkin aina olemassa)
- siirretään fallback-logiikka getOtsikko()-funktioon, jossa se vaikuttaa kaikkiin tutkinnonosiin eikä ainoastaan yhteisten tutkinnonosien osa-alueisiin
https://jira.eduuni.fi/browse/OY-4449
❗ **Katselmoijat tarkastavat, että yllä …
=> OY-4449: korjataan useat virhetilanteet tutkinnonosien tietojen haussa ePerusteista

shared/models/EPerusteetVastaus.ts
Vaikuttaa siltä, että ePerusteiden vastaukset ovat muuttuneet hiukan ja kun ne viedään EPerusteetVastaus-modeliin, siitä tulee mäppäysvirheitä.  Ongelmia aiheuttavat sekä kentät, jotka eivät aiemmin ole voineet olla `null`, että osaamistaso- ja arviointiKriteerit-kentät, joiden muoto on muuttunut merkkijonosta rakenteiseksi dataksi.
Näiden korjaaminen sai tutkinnonosien nimet näkymään ainakin deviympäristössä: https://jira.eduuni.fi/browse/EH-1546?focusedId=247521&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-247521
https://jira.eduuni.fi/browse/EH-1546
❗ **Katselmoijat tarkastavat, että yllä mainitut kohdat toteutuvat**
- Jos muutoksilla voi jotain rikkoessaan olla kauaskantoiset vaikutukset, kannattaa muutokset hyväksyttää useammalla katselmoijalla
=> EH-1546: Map changed API response to ePerusteetVastaus

virkailija/src/routes/LuoHOKS.tsx, virkailija/translations.json
Vaihdetaan ehoks-ui käyttämään session storagea välivarastona hoksia luodessa. Aiemmin käytössä on ollut local storage, jolla ei ole vanhenemisaikaa. On siis mahdollista, että syötettyä (tallentamatonta) henkilötietoa on voinut jäädä selaimen local storageen pidemmäksikin aikaa. Session storage tyhjenee, kun selaimen kyseinen välilehti suljetaan.
Tällä muutoksella on sellainen sivuvaikutus, että jos aiemmin käyttäjä on ollut syöttämässä uuden hoksin tietoja selaimen yhdellä välilehdellä ja on avannut ehoksin toiseen välilehteen, hän on voinut jatkaa tuon kyseisen hoksin täyttöä toisella välilehdellä (tai jopa uudelleenkirjautumisen jälkeenkin uudessa ikkunassa). Muutoksen käyttöönoton jälkeen tämä ei enää ole mahdollista, vaan uuden hoksin syöttäminen pitää tehdä loppuun sillä samalla …
=> OY-4489: Käytä session storagea hoksin välivarastona

shared/models/HOKS.ts, shared/stores/TranslationStore/defaultMessages.json, virkailija/src/routes/KoulutuksenJarjestaja.tsx
Cherry-pickattu seuraavat commitit:
- https://github.com/Opetushallitus/ehoks-ui/pull/452/commits/5e846015c8acebf385a9f38a7970d905eaad5c53 (korjaa tähän liittyvän konsoliin tuleen virheen)
- https://github.com/Opetushallitus/ehoks-ui/pull/452/commits/308d68dd2c34c0e4e414a92ef707f9381c63ec36 (korjaa jokusen herjan konsoliin käännöstekstien puuttumisesta)
- https://github.com/Opetushallitus/ehoks-ui/pull/452/commits/433ac921a5c4c143df106af8bcabc53d7dc58ef7 (`fireImmediately`-lippu tais olla turha, ainakin mun aiempien testailujen mukaan)
Commitin https://github.com/Opetushallitus/ehoks-ui/pull/452/commits/1244dd1e9b861fa160913c34a57e6587028affee jätin pois, koska en testatessa nähnyt consolissa ainakaan ylimääräisiä virheitä :thinking:
=> OY-4352: Small fixes that were included in #452 but not in #459

virkailija/src/routes/KoulutuksenJarjestaja.tsx, virkailija/src/routes/KoulutuksenJarjestaja/KoulutuksenJarjestajaHOKS.tsx, virkailija/src/routes/KoulutuksenJarjestaja/Opiskelija.tsx, virkailija/src/routes/Raportit.tsx
Jotta pääkäyttäjän raporttinäkymän linkit HOKSeihin toimivat oikein, pitää oppilaitos-oid välittää APIsta käyttöliittymälle.
Korjasin samalla myös spinnerin asettelun HOKSia ladattaessa.
=> EH-1682: Käytä rajapinnan oppilaitos-oidia pääkäyttäjän raporttinäkymässä

virkailija/src/routes/MuokkaaHOKS.tsx
Kun hoksia ollaan muokkaamassa, ladataan hoksin tiedot uudelleen tallentamisen jälkeen, jotta lisätystä työpaikkajaksosta ei tule duplikaattia (lähinnä ettei sille generoidu uutta yksilöivää id:tä).
=> EH-1709: Lataa hoksin tiedot uudelleen muokkauksen jälkeen
